Repository threatgrid/ctim, pull requests merged in 2018-08, with the labels that each got.

#213 Weakness CWE changes
  project.clj
  src/ctim/schemas/weakness.cljc
Labels: review

#215 Bundle Vulnerability support
  src/ctim/examples/bundles.cljc
  src/ctim/schemas/bundle.cljc
Labels: review

#216 NVD importer requirement changes
  doc/json/bundle.json
  doc/json/casebook.json
  doc/json/vulnerability.json
  doc/structures/bundle.md
  doc/structures/casebook.md
  doc/structures/vulnerability.md
  doc/structures/weakness.md
  src/ctim/examples/vulnerabilities.cljc
  src/ctim/schemas/vocabularies.cljc
  src/ctim/schemas/vulnerability.cljc
Labels: in progress, review

#217 Add an observable type for ODNS identities
  doc/structures/bundle.md
  doc/structures/casebook.md
  doc/structures/judgement.md
  doc/structures/sighting.md
  doc/structures/verdict.md
  src/ctim/schemas/common.cljc
  src/ctim/schemas/vocabularies.cljc
Labels: enhancement, review
